# Generated by Django 6.0.2 on 2026-02-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_participant_question_response_delete_surveyresponse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='SurveyResponse',
        ),
    ]
